"""
Search endpoint — main query interface.
"""
import sys
import os
import time

from fastapi import APIRouter, HTTPException

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from api.models import SearchRequest, SearchResponse
from agents.graph import run_agent

router = APIRouter(prefix="/api")


@router.post("/search", response_model=SearchResponse)
def search_query(req: SearchRequest):
    """Execute a persona-driven search with optional NL explanation.

    Returns ranked results, graph data, and optionally a natural language
    explanation generated by GPT-4o through the persona's lens.
    """
    t_start = time.time()

    valid_personas = {"value_investor", "pe_firm", "growth_vc", "strategic_acquirer", "enterprise_buyer"}
    if req.persona not in valid_personas:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid persona '{req.persona}'. Must be one of: {', '.join(sorted(valid_personas))}",
        )

    try:
        result = run_agent(
            query=req.query,
            persona=req.persona,
            include_explanation=req.include_explanation,
            all_personas=req.all_personas,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Agent error: {e}")

    if "error" in result and not result.get("results"):
        raise HTTPException(status_code=500, detail=result["error"])

    # Inject total elapsed time
    elapsed = int((time.time() - t_start) * 1000)
    if "metadata" in result:
        result["metadata"]["total_elapsed_ms"] = elapsed

    return result
